### PR TITLE
Update BingMapsCustomer.Table.al

### PR DESCRIPTION
**Pull request by jonaswre**

### CODE REVIEW

**Comment by jonaswre** [comment]
@freddydk can you accept me?

**Comment by freddydk** [comment]
> @freddydk can you accept me?

Accepted to run the PR handler to see the process.
Thanks for submitting.
I did find and fix a bug, which is why I re-ran the workflow (if you noticed)

**Comment by freddydk** [comment]
@jonaswre - I will obviously close the PR once you have seen the process here.

**Comment by freddydk** [comment]
BTW - I did find an error in the calculated workflow details link here:
image

It should have taken you to the job in the workflow - will fix that.

**Comment by jonaswre** [comment]
> > @freddydk can you accept me?
> 
> Accepted to run the PR handler to see the process.
> Thanks for submitting.
> I did find and fix a bug, which is why I re-ran the workflow (if you noticed)

Of course I meant you should allow me to run the workflow. I'll close it now. I think I've seen enough. Thanks

**Pull request closed without merging**
